# Generated by Django 6.0.2 on 2026-02-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0003_folder_studymaterial_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_materials.folder'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='pdf_file',
            field=models.FileField(upload_to='user_pdfs/'),
        ),
    ]
