# Generated by Django 6.0.2 on 2026-02-26 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0004_studymaterial_is_pinned_alter_folder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='study_materials.folder'),
        ),
    ]
